# Generated by Django 4.1.2 on 2024-09-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_table',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=40)),
                ('user_designation', models.CharField(max_length=7)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('post_text', models.TextField()),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
