# Generated by Django 5.1.1 on 2024-09-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_table',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='post_table',
            name='lname',
        ),
    ]
