# Generated by Django 5.1.1 on 2024-09-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_discussion_post_remove_discussionpost_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_table',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=40)),
                ('user_designation', models.CharField(max_length=7)),
                ('post_text', models.TextField()),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
